spring.application.name=school2
spring.datasource.url=jdbc:mysql://localhost:3306/schoolapi?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
